name: Flutter CI (Testing)

on:
  push:
    branches: [ "**" ] # Runs on all branches
  pull_request:
    branches: [ "main" ]

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Check Formatting
        # run: dart format --output=none --set-exit-if-changed .
        # Removing --set-exit-if-changed means it will show you what's wrong 
        # but won't stop the build.
        run: dart format --output=none .

      - name: Analyze Code
        run: flutter analyze

      - name: Run Unit Tests
        run: flutter test --coverage

    #   - name: Build Debug APK (Dry Run)
    #     run: flutter build apk --debug